//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneratePinsForPandora.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DtaResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DtaResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeneratePinsForPandora.Resource.DtaResource", typeof(DtaResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to { &quot;102269&quot;: { &quot;id&quot;: &quot;102269&quot;, &quot;parent_id&quot;: 0, &quot;level&quot;: 4, &quot;name&quot;: &quot;Москва&quot;, &quot;relations&quot;: [{ &quot;id&quot;: &quot;2263059&quot;, &quot;level&quot;: 5, &quot;name&quot;: &quot;Троицкий административный округ&quot; }, { &quot;id&quot;: &quot;2263058&quot;, &quot;level&quot;: 5, &quot;name&quot;: &quot;Новомосковский административный округ&quot; }, { &quot;id&quot;: &quot;226149&quot;, &quot;level&quot;: 5, &quot;name&quot;: &quot;Западный административный округ&quot; }, { &quot;id&quot;: &quot;1320234&quot;, &quot;level&quot;: 5, &quot;name&quot;: &quot;Восточный административный округ&quot; }, { &quot;id&quot;: &quot;1278703&quot;, &quot;level&quot;: 5, &quot;name&quot;: &quot;Юго-Восточный административный округ&quot; }, { &quot;id&quot;: &quot;162903&quot;, &quot;level&quot;: 5, &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Regions {
            get {
                return ResourceManager.GetString("Regions", resourceCulture);
            }
        }
    }
}
